# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/rextwo/Desktop/d.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addDialog(object):
    def setupUi(self, addDialog):
        addDialog.setObjectName("addDialog")
        addDialog.resize(271, 204)
        self.layoutWidget = QtWidgets.QWidget(addDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 251, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frmNim = QtWidgets.QLineEdit(self.layoutWidget)
        self.frmNim.setInputMask("")
        self.frmNim.setText("")
        self.frmNim.setObjectName("frmNim")
        self.verticalLayout.addWidget(self.frmNim)
        self.frmNama = QtWidgets.QLineEdit(self.layoutWidget)
        self.frmNama.setInputMask("")
        self.frmNama.setText("")
        self.frmNama.setObjectName("frmNama")
        self.verticalLayout.addWidget(self.frmNama)
        self.frmJurusan = QtWidgets.QComboBox(self.layoutWidget)
        self.frmJurusan.setEditable(False)
        self.frmJurusan.setObjectName("frmJurusan")
        self.frmJurusan.addItem("")
        self.frmJurusan.addItem("")
        self.frmJurusan.addItem("")
        self.frmJurusan.addItem("")
        self.frmJurusan.addItem("")
        self.verticalLayout.addWidget(self.frmJurusan)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(addDialog)
        self.frmJurusan.setCurrentIndex(0)
        self.buttonBox.accepted.connect(addDialog.accept)
        self.buttonBox.rejected.connect(addDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(addDialog)

    def retranslateUi(self, addDialog):
        _translate = QtCore.QCoreApplication.translate
        addDialog.setWindowTitle(_translate("addDialog", "Add Data"))
        self.frmNim.setPlaceholderText(_translate("addDialog", "Masukkan NIM"))
        self.frmNama.setPlaceholderText(_translate("addDialog", "Masukkan Nama"))
        self.frmJurusan.setCurrentText(_translate("addDialog", "- Pilih Jurusan -"))
        self.frmJurusan.setItemText(0, _translate("addDialog", "- Pilih Jurusan -"))
        self.frmJurusan.setItemText(1, _translate("addDialog", "RPL"))
        self.frmJurusan.setItemText(2, _translate("addDialog", "TI"))
        self.frmJurusan.setItemText(3, _translate("addDialog", "SI"))
        self.frmJurusan.setItemText(4, _translate("addDialog", "DKV"))
        self.lineEdit_4.setPlaceholderText(_translate("addDialog", "Masukkan No.Telp"))
