# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/rextwo/Desktop/e.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editDialog(object):
    def setupUi(self, editDialog):
        editDialog.setObjectName("editDialog")
        editDialog.resize(252, 192)
        self.widget = QtWidgets.QWidget(editDialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 231, 171))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.frmNama = QtWidgets.QLineEdit(self.widget)
        self.frmNama.setInputMask("")
        self.frmNama.setText("")
        self.frmNama.setObjectName("frmNama")
        self.verticalLayout.addWidget(self.frmNama)
        self.frmJurusan = QtWidgets.QComboBox(self.widget)
        self.frmJurusan.setEditable(False)
        self.frmJurusan.setObjectName("frmJurusan")
        self.frmJurusan.addItem("")
        self.frmJurusan.addItem("")
        self.frmJurusan.addItem("")
        self.frmJurusan.addItem("")
        self.frmJurusan.addItem("")
        self.verticalLayout.addWidget(self.frmJurusan)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(editDialog)
        self.frmJurusan.setCurrentIndex(0)
        self.buttonBox.accepted.connect(editDialog.accept)
        self.buttonBox.rejected.connect(editDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(editDialog)

    def retranslateUi(self, editDialog):
        _translate = QtCore.QCoreApplication.translate
        editDialog.setWindowTitle(_translate("editDialog", "Edit Data"))
        self.comboBox.setItemText(0, _translate("editDialog", "- Pilih NIM -"))
        self.frmNama.setPlaceholderText(_translate("editDialog", "Masukkan Nama"))
        self.frmJurusan.setCurrentText(_translate("editDialog", "- Pilih Jurusan -"))
        self.frmJurusan.setItemText(0, _translate("editDialog", "- Pilih Jurusan -"))
        self.frmJurusan.setItemText(1, _translate("editDialog", "RPL"))
        self.frmJurusan.setItemText(2, _translate("editDialog", "TI"))
        self.frmJurusan.setItemText(3, _translate("editDialog", "SI"))
        self.frmJurusan.setItemText(4, _translate("editDialog", "DKV"))
        self.lineEdit_4.setPlaceholderText(_translate("editDialog", "Masukkan No.Telp"))
